### ISSUE TITLE
Count archived_threads as well

### ISSUE THREAD

**Issue by hoangbn** [KMChris/messenger-counter#2]
Currently only messages under `messages/inbox/` are counted. You may want to include `messages/archived_threads/` count too (either together in `messages.json`, or separately in `messages-archived.json`), since a lot of conversations end up archived

**Comment by FanisDeligiannis** [comment]
Hello! I wanted the same, so I went ahead and implemented it. I also did a pull request for you: #3

**Comment by KMChris** [comment]
Resolved by #3
