### ISSUE TITLE
Can't find message_i.json

### ISSUE THREAD

**Issue by TimotheeWright** [KMChris/messenger-counter#4]
I don't see the message_i.json in messages/inbox/ after download. Either i'm missing something or this module cannot be used anymore :/

**Comment by KMChris** [comment]
Facebook sends data in multiple .zip files, messages usually appear in only one of them. Try downloading another from the available files.

**Comment by TimotheeWright** [comment]
Actually this was fix downloading year by year instead of all data all at once. If that can help someone. Also wrote a script to get the json for each year and aggregate all of them in 1 json, sorted by number of messages.

If that can be useful to someone i'll happily share it
