### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by albertfgu** [KMChris/messenger-counter#6]
I downloaded the package with `pip install messenger-counter` and then ran `python -m mc facebook-<user>.zip`, and got the error
```
usage: mc.py [-h] command ...
mc.py: error: argument command: invalid choice: 'facebook-<user>zip' (choose from 'count', 'stats', 'user', 'yearly', 'daily', 'hours')
```

**Comment by KMChris** [comment]
That's because there is an older version on pip than here on github, you can see the description on pypi for that version, or download the source code from here.
